// PowerSync Schema for FlutterFlow
//
// INSTRUCTIONS:
// 1. Copy this entire file content
// 2. In FlutterFlow: App Settings → Project Dependencies → FlutterFlow Libraries
// 3. Find PowerSync library → Click Configure
// 4. Paste this code into the "PowerSyncSchema" field
// 5. Click Save
//
// This schema defines 20 tables for offline-first medical data operations
// including user profiles, vital signs, lab results, prescriptions, appointments, and more.

import 'package:powersync/powersync.dart';

const schema = Schema([
  // Core user tables
  Table('users', [
    Column.text('id'),
    Column.text('email'),
    Column.text('display_name'),
    Column.text('phone_number'),
    Column.text('firebase_uid'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),

  Table('patient_profiles', [
    Column.text('id'),
    Column.text('user_id'),
    Column.text('first_name'),
    Column.text('last_name'),
    Column.text('date_of_birth'),
    Column.text('gender'),
    Column.text('blood_type'),
    Column.text('address'),
    Column.text('city'),
    Column.text('state'),
    Column.text('postal_code'),
    Column.text('country'),
    Column.text('emergency_contact_name'),
    Column.text('emergency_contact_phone'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),

  Table('medical_provider_profiles', [
    Column.text('id'),
    Column.text('user_id'),
    Column.text('first_name'),
    Column.text('last_name'),
    Column.text('specialty'),
    Column.text('license_number'),
    Column.text('npi_number'),
    Column.text('years_of_experience'),
    Column.integer('rating'),
    Column.text('facility_id'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),

  Table('facility_admin_profiles', [
    Column.text('id'),
    Column.text('user_id'),
    Column.text('first_name'),
    Column.text('last_name'),
    Column.text('facility_id'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),

  // Electronic Health Records
  Table('electronic_health_records', [
    Column.text('id'),
    Column.text('patient_id'),
    Column.text('ehr_id'),
    Column.text('ehr_status'),
    Column.text('system_id'),
    Column.text('subject_namespace'),
    Column.text('ehrbase_created_at'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),

  Table('ehr_compositions', [
    Column.text('id'),
    Column.text('ehr_id'),
    Column.text('patient_id'),
    Column.text('template_id'),
    Column.text('composition_uid'),
    Column.text('archetype_node_id'),
    Column.text('composition_data'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),

  // Medical Data Tables
  Table('vital_signs', [
    Column.text('id'),
    Column.text('patient_id'),
    Column.real('systolic_bp'),
    Column.real('diastolic_bp'),
    Column.real('heart_rate'),
    Column.real('temperature'),
    Column.real('respiratory_rate'),
    Column.real('oxygen_saturation'),
    Column.real('weight'),
    Column.real('height'),
    Column.real('bmi'),
    Column.text('recorded_at'),
    Column.text('recorded_by'),
    Column.text('notes'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),

  Table('lab_results', [
    Column.text('id'),
    Column.text('patient_id'),
    Column.text('test_name'),
    Column.text('test_code'),
    Column.text('result_value'),
    Column.text('result_unit'),
    Column.text('reference_range'),
    Column.text('status'),
    Column.text('interpretation'),
    Column.text('ordered_by'),
    Column.text('performed_by'),
    Column.text('laboratory_name'),
    Column.text('specimen_type'),
    Column.text('collection_date'),
    Column.text('result_date'),
    Column.text('notes'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),

  Table('prescriptions', [
    Column.text('id'),
    Column.text('patient_id'),
    Column.text('medication_name'),
    Column.text('medication_code'),
    Column.text('dosage'),
    Column.text('frequency'),
    Column.text('route'),
    Column.text('duration'),
    Column.integer('quantity'),
    Column.integer('refills'),
    Column.text('prescriber_id'),
    Column.text('pharmacy_name'),
    Column.text('start_date'),
    Column.text('end_date'),
    Column.text('status'),
    Column.text('instructions'),
    Column.text('notes'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),

  Table('immunizations', [
    Column.text('id'),
    Column.text('patient_id'),
    Column.text('vaccine_name'),
    Column.text('vaccine_code'),
    Column.text('dose_number'),
    Column.text('route'),
    Column.text('site'),
    Column.text('lot_number'),
    Column.text('manufacturer'),
    Column.text('administered_by'),
    Column.text('administered_date'),
    Column.text('expiration_date'),
    Column.text('reaction'),
    Column.text('notes'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),

  Table('allergies', [
    Column.text('id'),
    Column.text('patient_id'),
    Column.text('allergen_name'),
    Column.text('allergen_code'),
    Column.text('allergen_type'),
    Column.text('reaction'),
    Column.text('severity'),
    Column.text('onset_date'),
    Column.text('status'),
    Column.text('notes'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),

  Table('medical_records', [
    Column.text('id'),
    Column.text('patient_id'),
    Column.text('record_type'),
    Column.text('title'),
    Column.text('description'),
    Column.text('diagnosis_code'),
    Column.text('provider_id'),
    Column.text('facility_id'),
    Column.text('visit_date'),
    Column.text('document_url'),
    Column.text('status'),
    Column.text('notes'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),

  // Appointments
  Table('appointments', [
    Column.text('id'),
    Column.text('patient_id'),
    Column.text('provider_id'),
    Column.text('facility_id'),
    Column.text('appointment_date'),
    Column.text('appointment_time'),
    Column.integer('duration_minutes'),
    Column.text('appointment_type'),
    Column.text('status'),
    Column.text('reason'),
    Column.text('notes'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),

  // Facilities and Organizations
  Table('facilities', [
    Column.text('id'),
    Column.text('name'),
    Column.text('facility_type'),
    Column.text('address'),
    Column.text('city'),
    Column.text('state'),
    Column.text('postal_code'),
    Column.text('country'),
    Column.text('phone'),
    Column.text('email'),
    Column.text('website'),
    Column.text('organization_id'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),

  Table('organizations', [
    Column.text('id'),
    Column.text('name'),
    Column.text('organization_type'),
    Column.text('tax_id'),
    Column.text('address'),
    Column.text('city'),
    Column.text('state'),
    Column.text('postal_code'),
    Column.text('country'),
    Column.text('phone'),
    Column.text('email'),
    Column.text('website'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),

  // EHRbase Sync Queue
  Table('ehrbase_sync_queue', [
    Column.text('id'),
    Column.text('table_name'),
    Column.text('record_id'),
    Column.text('template_id'),
    Column.text('sync_type'),
    Column.text('sync_status'),
    Column.integer('retry_count'),
    Column.text('error_message'),
    Column.text('ehrbase_composition_id'),
    Column.text('data_snapshot'),
    Column.text('created_at'),
    Column.text('processed_at'),
    Column.text('last_retry_at'),
    Column.text('updated_at'),
  ]),

  // AI Conversations
  Table('ai_conversations', [
    Column.text('id'),
    Column.text('user_id'),
    Column.text('conversation_type'),
    Column.text('title'),
    Column.text('messages'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),

  // Documents
  Table('documents', [
    Column.text('id'),
    Column.text('patient_id'),
    Column.text('provider_id'),
    Column.text('document_type'),
    Column.text('title'),
    Column.text('description'),
    Column.text('file_path'),
    Column.text('file_size'),
    Column.text('mime_type'),
    Column.text('upload_date'),
    Column.text('status'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
]);
