AWSTemplateFormatVersion: '2010-09-09'
Description: 'MedZen Global Infrastructure - Route 53, IAM, KMS for Multi-Region Architecture'

Parameters:
  ProjectName:
    Type: String
    Default: medzen
    Description: Project name for resource naming

  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - staging
      - production
    Description: Deployment environment

  DomainName:
    Type: String
    Default: medzenhealth.app
    Description: Primary domain name

  PrimaryRegion:
    Type: String
    Default: af-south-1
    Description: Primary region for EHRbase

  SecondaryRegion:
    Type: String
    Default: eu-west-1
    Description: Secondary region for AI/Chime

  DRRegion:
    Type: String
    Default: us-east-1
    Description: Disaster recovery region

Resources:
  # ============================================
  # Route 53 Hosted Zone
  # ============================================
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName
      HostedZoneConfig:
        Comment: !Sub '${ProjectName} hosted zone for ${Environment}'

  # ============================================
  # Health Checks for Failover
  # ============================================
  EHRbaseHealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        FullyQualifiedDomainName: !Sub 'ehr.${DomainName}'
        Port: 443
        Type: HTTPS
        ResourcePath: /ehrbase/rest/status
        RequestInterval: 30
        FailureThreshold: 3
        EnableSNI: true
      HealthCheckTags:
        - Key: Name
          Value: !Sub '${ProjectName}-ehrbase-health-check'
        - Key: Environment
          Value: !Ref Environment

  AIHealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        FullyQualifiedDomainName: !Sub 'ai.${DomainName}'
        Port: 443
        Type: HTTPS
        ResourcePath: /health
        RequestInterval: 30
        FailureThreshold: 3
        EnableSNI: true
      HealthCheckTags:
        - Key: Name
          Value: !Sub '${ProjectName}-ai-health-check'
        - Key: Environment
          Value: !Ref Environment

  ChimeHealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        FullyQualifiedDomainName: !Sub 'meetings.${DomainName}'
        Port: 443
        Type: HTTPS
        ResourcePath: /health
        RequestInterval: 30
        FailureThreshold: 3
        EnableSNI: true
      HealthCheckTags:
        - Key: Name
          Value: !Sub '${ProjectName}-chime-health-check'
        - Key: Environment
          Value: !Ref Environment

  # ============================================
  # IAM Roles for Cross-Region Operations
  # ============================================

  # Cross-Region Replication Role for S3
  S3ReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-s3-replication-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3ReplicationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetReplicationConfiguration
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${ProjectName}-*'
              - Effect: Allow
                Action:
                  - s3:GetObjectVersionForReplication
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectVersionTagging
                Resource:
                  - !Sub 'arn:aws:s3:::${ProjectName}-*/*'
              - Effect: Allow
                Action:
                  - s3:ReplicateObject
                  - s3:ReplicateDelete
                  - s3:ReplicateTags
                Resource:
                  - !Sub 'arn:aws:s3:::${ProjectName}-*/*'

  # Lambda Execution Role for Multi-Region
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-lambda-execution-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                  - bedrock:GetFoundationModel
                  - bedrock:ListFoundationModels
                  - bedrock:ApplyGuardrail
                Resource: '*'
        - PolicyName: ChimeAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - chime:CreateMeeting
                  - chime:DeleteMeeting
                  - chime:GetMeeting
                  - chime:ListMeetings
                  - chime:CreateAttendee
                  - chime:DeleteAttendee
                  - chime:GetAttendee
                  - chime:ListAttendees
                  - chime:CreateMediaCapturePipeline
                  - chime:DeleteMediaCapturePipeline
                  - chime:GetMediaCapturePipeline
                  - chime:ListMediaCapturePipelines
                Resource: '*'
        - PolicyName: TranslateAndComprehend
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - translate:TranslateText
                  - translate:DetectDominantLanguage
                  - comprehendmedical:DetectEntitiesV2
                  - comprehendmedical:InferICD10CM
                  - comprehendmedical:InferRxNorm
                  - comprehend:DetectDominantLanguage
                Resource: '*'
        - PolicyName: TranscribeAndPolly
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - transcribe:StartTranscriptionJob
                  - transcribe:GetTranscriptionJob
                  - transcribe:StartMedicalTranscriptionJob
                  - transcribe:GetMedicalTranscriptionJob
                  - polly:SynthesizeSpeech
                  - polly:DescribeVoices
                Resource: '*'
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${ProjectName}-*'
                  - !Sub 'arn:aws:s3:::${ProjectName}-*/*'
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !Sub 'arn:aws:dynamodb:*:${AWS::AccountId}:table/${ProjectName}-*'
        - PolicyName: KMSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource:
                  - !Sub 'arn:aws:kms:*:${AWS::AccountId}:key/*'

  # ECS Task Execution Role
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-ecs-task-execution-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub 'arn:aws:secretsmanager:*:${AWS::AccountId}:secret:${ProjectName}/*'
        - PolicyName: KMSDecrypt
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource:
                  - !Sub 'arn:aws:kms:*:${AWS::AccountId}:key/*'

  # Cross-Region RDS Replication Role
  RDSReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-rds-replication-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: rds.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: RDSReplicationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource:
                  - !Sub 'arn:aws:kms:*:${AWS::AccountId}:key/*'

  # ============================================
  # SNS Topics for Cross-Region Alerts
  # ============================================
  AlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-global-alerts'
      DisplayName: !Sub '${ProjectName} Global Alerts'
      Tags:
        - Key: Environment
          Value: !Ref Environment

  AlertsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudwatch.amazonaws.com
                - events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref AlertsTopic
      Topics:
        - !Ref AlertsTopic

  # ============================================
  # DynamoDB Global Table for Audit Logs
  # ============================================
  AuditLogsTable:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      TableName: !Sub '${ProjectName}-audit-logs'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1pk
          AttributeType: S
        - AttributeName: gsi1sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: gsi1
          KeySchema:
            - AttributeName: gsi1pk
              KeyType: HASH
            - AttributeName: gsi1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Replicas:
        - Region: !Ref PrimaryRegion
          PointInTimeRecoverySpecification:
            PointInTimeRecoveryEnabled: true
          Tags:
            - Key: Environment
              Value: !Ref Environment
        - Region: !Ref SecondaryRegion
          PointInTimeRecoverySpecification:
            PointInTimeRecoveryEnabled: true
          Tags:
            - Key: Environment
              Value: !Ref Environment
        - Region: !Ref DRRegion
          PointInTimeRecoverySpecification:
            PointInTimeRecoveryEnabled: true
          Tags:
            - Key: Environment
              Value: !Ref Environment

  # ============================================
  # Secrets Manager for Cross-Region Secrets
  # ============================================
  DatabaseCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/database/credentials'
      Description: Database credentials for EHRbase
      GenerateSecretString:
        SecretStringTemplate: '{"username": "ehrbase_admin"}'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Environment
          Value: !Ref Environment

  EHRbaseCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/ehrbase/credentials'
      Description: EHRbase application credentials
      GenerateSecretString:
        SecretStringTemplate: '{"username": "ehrbase_user"}'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # ============================================
  # CloudWatch Log Groups (Central)
  # ============================================
  CentralLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/${ProjectName}/global'
      RetentionInDays: 90
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  HostedZoneId:
    Description: Route 53 Hosted Zone ID
    Value: !Ref HostedZone
    Export:
      Name: !Sub '${ProjectName}-HostedZoneId'

  HostedZoneNameServers:
    Description: Route 53 Name Servers
    Value: !Join [', ', !GetAtt HostedZone.NameServers]

  EHRbaseHealthCheckId:
    Description: EHRbase Health Check ID
    Value: !Ref EHRbaseHealthCheck
    Export:
      Name: !Sub '${ProjectName}-EHRbaseHealthCheckId'

  AIHealthCheckId:
    Description: AI Health Check ID
    Value: !Ref AIHealthCheck
    Export:
      Name: !Sub '${ProjectName}-AIHealthCheckId'

  ChimeHealthCheckId:
    Description: Chime Health Check ID
    Value: !Ref ChimeHealthCheck
    Export:
      Name: !Sub '${ProjectName}-ChimeHealthCheckId'

  LambdaExecutionRoleArn:
    Description: Lambda Execution Role ARN
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${ProjectName}-LambdaExecutionRoleArn'

  ECSTaskExecutionRoleArn:
    Description: ECS Task Execution Role ARN
    Value: !GetAtt ECSTaskExecutionRole.Arn
    Export:
      Name: !Sub '${ProjectName}-ECSTaskExecutionRoleArn'

  S3ReplicationRoleArn:
    Description: S3 Replication Role ARN
    Value: !GetAtt S3ReplicationRole.Arn
    Export:
      Name: !Sub '${ProjectName}-S3ReplicationRoleArn'

  RDSReplicationRoleArn:
    Description: RDS Replication Role ARN
    Value: !GetAtt RDSReplicationRole.Arn
    Export:
      Name: !Sub '${ProjectName}-RDSReplicationRoleArn'

  AlertsTopicArn:
    Description: Global Alerts SNS Topic ARN
    Value: !Ref AlertsTopic
    Export:
      Name: !Sub '${ProjectName}-AlertsTopicArn'

  AuditLogsTableName:
    Description: DynamoDB Global Audit Logs Table Name
    Value: !Ref AuditLogsTable
    Export:
      Name: !Sub '${ProjectName}-AuditLogsTableName'

  DatabaseCredentialsArn:
    Description: Database Credentials Secret ARN
    Value: !Ref DatabaseCredentials
    Export:
      Name: !Sub '${ProjectName}-DatabaseCredentialsArn'

  EHRbaseCredentialsArn:
    Description: EHRbase Credentials Secret ARN
    Value: !Ref EHRbaseCredentials
    Export:
      Name: !Sub '${ProjectName}-EHRbaseCredentialsArn'
