-- Migration: Add unique identifier columns to all user profile tables
-- Format:
--   Patient: PA-12345 (5 digits)
--   Provider: PR-{role}-12345 (role = 2-letter code like NR for nurse)
--   Facility Admin: FA-12345 (5 digits)
--   System Admin: SA-12345 (5 digits)

-- =====================================================
-- 1. PATIENT PROFILES
-- =====================================================

-- Check if patient_number column already exists, if not add it
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
    AND table_name = 'patient_profiles'
    AND column_name = 'patient_number'
  ) THEN
    ALTER TABLE public.patient_profiles
    ADD COLUMN patient_number TEXT;
  END IF;
END $$;

-- Add unique constraint if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'patient_profiles_patient_number_key'
  ) THEN
    ALTER TABLE public.patient_profiles
    ADD CONSTRAINT patient_profiles_patient_number_key UNIQUE (patient_number);
  END IF;
END $$;

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_patient_profiles_patient_number
ON public.patient_profiles(patient_number);

-- Add comment
COMMENT ON COLUMN public.patient_profiles.patient_number IS
'Unique patient identifier in format PA-12345. Auto-generated by FlutterFlow custom action.';

-- =====================================================
-- 2. MEDICAL PROVIDER PROFILES
-- =====================================================

-- Check if provider_number column already exists, if not add it
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
    AND table_name = 'medical_provider_profiles'
    AND column_name = 'provider_number'
  ) THEN
    ALTER TABLE public.medical_provider_profiles
    ADD COLUMN provider_number TEXT;
  END IF;
END $$;

-- Add unique constraint if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'medical_provider_profiles_provider_number_key'
  ) THEN
    ALTER TABLE public.medical_provider_profiles
    ADD CONSTRAINT medical_provider_profiles_provider_number_key UNIQUE (provider_number);
  END IF;
END $$;

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_medical_provider_profiles_provider_number
ON public.medical_provider_profiles(provider_number);

-- Add comment
COMMENT ON COLUMN public.medical_provider_profiles.provider_number IS
'Unique provider identifier in format PR-{role}-12345 (e.g., PR-NR-12345 for nurse). Auto-generated by FlutterFlow custom action.';

-- =====================================================
-- 3. FACILITY ADMIN PROFILES
-- =====================================================

-- Check if admin_number column already exists, if not add it
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
    AND table_name = 'facility_admin_profiles'
    AND column_name = 'admin_number'
  ) THEN
    ALTER TABLE public.facility_admin_profiles
    ADD COLUMN admin_number TEXT;
  END IF;
END $$;

-- Add unique constraint if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'facility_admin_profiles_admin_number_key'
  ) THEN
    ALTER TABLE public.facility_admin_profiles
    ADD CONSTRAINT facility_admin_profiles_admin_number_key UNIQUE (admin_number);
  END IF;
END $$;

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_facility_admin_profiles_admin_number
ON public.facility_admin_profiles(admin_number);

-- Add comment
COMMENT ON COLUMN public.facility_admin_profiles.admin_number IS
'Unique facility admin identifier in format FA-12345. Auto-generated by FlutterFlow custom action.';

-- =====================================================
-- 4. SYSTEM ADMIN PROFILES
-- =====================================================

-- Check if admin_number column already exists, if not add it
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
    AND table_name = 'system_admin_profiles'
    AND column_name = 'admin_number'
  ) THEN
    ALTER TABLE public.system_admin_profiles
    ADD COLUMN admin_number TEXT;
  END IF;
END $$;

-- Add unique constraint if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'system_admin_profiles_admin_number_key'
  ) THEN
    ALTER TABLE public.system_admin_profiles
    ADD CONSTRAINT system_admin_profiles_admin_number_key UNIQUE (admin_number);
  END IF;
END $$;

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_system_admin_profiles_admin_number
ON public.system_admin_profiles(admin_number);

-- Add comment
COMMENT ON COLUMN public.system_admin_profiles.admin_number IS
'Unique system admin identifier in format SA-12345. Auto-generated by FlutterFlow custom action.';

-- =====================================================
-- NOTES
-- =====================================================
--
-- These columns are nullable by design because:
-- 1. Numbers are generated client-side in FlutterFlow custom actions
-- 2. Migration allows for gradual backfill of existing records
-- 3. New records MUST have these values set during profile creation
--
-- The unique constraint prevents duplicates even if retry logic fails.
--
-- Format specifications:
-- - Patient: PA-{5 random digits} e.g., PA-12345
-- - Provider: PR-{2-letter role}-{5 random digits} e.g., PR-NR-12345
-- - Facility Admin: FA-{5 random digits} e.g., FA-12345
-- - System Admin: SA-{5 random digits} e.g., SA-12345
