-- Migration: Create soap_notes table for storing SOAP note drafts
-- Description: Stores SOAP note drafts generated by Claude Opus via AWS Bedrock

-- =====================================================
-- Create soap_notes table
-- =====================================================
CREATE TABLE IF NOT EXISTS soap_notes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES video_call_sessions(id) ON DELETE CASCADE,
  appointment_id UUID NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
  call_transcript_id UUID REFERENCES call_transcripts(id) ON DELETE SET NULL,
  status VARCHAR(50) DEFAULT 'draft', -- draft, submitted, archived
  
  -- Chief complaint and history
  chief_complaint TEXT,
  
  -- SOAP sections (stored as JSONB for nested structure)
  subjective JSONB, -- Patient's description of symptoms, history
  objective JSONB, -- Clinical findings, vital signs, test results
  assessment JSONB, -- Diagnosis, clinical impression, differential diagnoses
  plan JSONB, -- Treatment plan, prescriptions, follow-up
  safety JSONB, -- Safety flags, red flags, allergies, contraindications
  
  -- AI generation metadata
  ai_generated_at TIMESTAMPTZ,
  ai_model_used VARCHAR(255),
  ai_raw_json JSONB, -- Full response from Claude for audit trail
  ai_generation_prompt_version VARCHAR(50),
  
  -- Clinician review
  requires_clinician_review BOOLEAN DEFAULT true,
  reviewed_by UUID REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  review_notes TEXT,
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  submitted_at TIMESTAMPTZ
);

-- Add comment for documentation
COMMENT ON TABLE soap_notes IS 'Stores AI-generated SOAP note drafts from video call transcripts, ready for clinician review and submission';

-- =====================================================
-- Create indexes for efficient queries
-- =====================================================
CREATE INDEX IF NOT EXISTS idx_soap_notes_session_id
  ON soap_notes(session_id);

CREATE INDEX IF NOT EXISTS idx_soap_notes_appointment_id
  ON soap_notes(appointment_id);

CREATE INDEX IF NOT EXISTS idx_soap_notes_status
  ON soap_notes(status);

CREATE INDEX IF NOT EXISTS idx_soap_notes_created_at
  ON soap_notes(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_soap_notes_reviewed_by
  ON soap_notes(reviewed_by);

-- Composite indexes for common queries
CREATE INDEX IF NOT EXISTS idx_soap_notes_session_status
  ON soap_notes(session_id, status);

CREATE INDEX IF NOT EXISTS idx_soap_notes_appointment_status
  ON soap_notes(appointment_id, status);

-- =====================================================
-- Enable Row Level Security
-- =====================================================
ALTER TABLE soap_notes ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (for idempotency)
DROP POLICY IF EXISTS "soap_notes_select_access" ON soap_notes;
DROP POLICY IF EXISTS "soap_notes_insert_access" ON soap_notes;
DROP POLICY IF EXISTS "soap_notes_update_access" ON soap_notes;

-- RLS Policies
-- Select: Users can view SOAP notes for sessions they participated in
CREATE POLICY "soap_notes_select_access" ON soap_notes
FOR SELECT USING (
  auth.uid() IS NULL OR
  session_id IN (
    SELECT id FROM video_call_sessions
    WHERE provider_id = auth.uid() OR patient_id = auth.uid()
  )
);

-- Insert: Only service role can insert (called from edge functions)
CREATE POLICY "soap_notes_insert_access" ON soap_notes
FOR INSERT WITH CHECK (auth.role() = 'service_role');

-- Update: Only service role or the clinician reviewing can update
CREATE POLICY "soap_notes_update_access" ON soap_notes
FOR UPDATE USING (
  auth.role() = 'service_role' OR
  (requires_clinician_review = true AND reviewed_by = auth.uid())
);

-- =====================================================
-- Grant permissions
-- =====================================================
GRANT SELECT ON soap_notes TO anon;
GRANT SELECT ON soap_notes TO authenticated;
GRANT ALL ON soap_notes TO service_role;
